apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cBeKat2+OvN+7PmShN+g0j/GJeShBbcpXHkol3a7VRI=,iv:zHn6bnelBtPFp+bNTx4p4gf6ZuBUqAfSFQX/1h1eIOM=,tag:xdTCMxerJdIrYp1qf3zwOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8ak86ksgcf7rwrt7ylv8y3e7d0xv25p0lr6dqd6htg3xq82y55qtue96k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhemVXdnJkcmxCc2Q3VlFy
            WjNHREpHanR2T25MNVFHeWRoeCtjTC9QTXlBCkt2SDFtZXVmZU9HN0R5cldPd3VC
            cFJKM2cvbERMS3MwdGUrY004RGFHdFEKLS0tIHFRS3htUGtXeEM0MTB2d1ZNWmN0
            VGNtTDNFSGpyRjMyRndMWElMb0pvZlUKb99bwVzqdbFOOwuDaHnUJ2f25CAgceeu
            aNL3QyXKI2FGUxidoS8MB278U789rtSNKcFO1X7xotCldiUF3CIYkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T12:32:11Z"
    mac: ENC[AES256_GCM,data:dmA5km00IevM4zLvyI2P977YGCBDF2AXdDkNv/5r4n2b+5WgPD4UzuHv9qlcrc2gbE4eJgOuZ1JMNdx72eeWW3rAtMRjumRmzfoplSaI4S2uxIOYC36cml9y8npDM0p/R8CbQf5azhg2QulPmOtEXls7gXd1x69+jeXnwZv1Hi4=,iv:K5y8BKkBClfYWrktEtenI9sXR+8T43UAeAnQNoGXryk=,tag:fdQYpK8JPjII4PxMAQWPeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
